server:
  port: 8088
spring:
  application:
    name: mall-order
dubbo:
  scan:
    base-packages: io.dobson.mall.order.service.impl
  registry:
    address: zookeeper://localhost:2181
  protocol:
    name: dubbo
    port: 12345
  metadata-report:
    address: zookeeper://localhost:2181

